#!/usr/bin/env bash
# Transfers a file from a client to a server

# checks if number of arguments is less than 3
if [ $# -lt 3 ];
then
    #prints usage
    echo "Usage: 0-tranfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;

#checks if number of arguments is greater than or equal to 4
if [ $# -ge 4 ];
then
    #transfers file to server with strict host key checking disabled
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    #transfers file to server without ssh key
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
