#!/usr/bin/env bash
# Configuring Nginx server to listen to port 80 (shorter version)
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
